### ISSUE TITLE
Pallet File Required?

### ISSUE THREAD

**Issue by Oran26thRTI** [queueRAM/Texture64#12]
I am sorry if this sounds stupid but I have tried figuring this out on my own but not 100% sure so figured I would ask here.

I am trying to open a game to look at the images, the file format is .z64. I for the life of me cannot find any images in it and have tried all of the Codec options.

Am I missing something?

I would truly appreciate some help.

**Comment by queueRAM** [comment]
There is no file system in N64 games and some games have compressed blocks. The texture viewer doesn't understand any of this and you'll have to manually find the textures for a specific game. Hope this helps!
