### ISSUE TITLE
limited functionality with drag-and-drop

### ISSUE THREAD

**Issue by notwa** [queueRAM/Texture64#3]
this had me scratching my head for a few minutes. pretty easy to reproduce:

* run a new instance of texture64
* drag and drop a file to load it
* try to scroll while hovering over any viewport, doesn't work
* left- or right-clicking has no effect either

workaround:
* use the Open dialog at least once

**Comment by queueRAM** [comment]
Thanks for the report. I looked at the code and think I spot the issue. Relative to drag-and-drop or opening a file from the command line, Ctrl+O calls additional functions after reading in the data to setup the window. I'll fix and validate this over the weekend.
