### ISSUE TITLE
Can't Right Click to bring up export menu Windows 10

### ISSUE THREAD

**Issue by binkers87** [queueRAM/Texture64#6]
For some reason on my Windows 10 PC I can't right click to bring up the export menu to export an image to .png etc.

**Comment by queueRAM** [comment]
Texture64 Export menu is working fine for me in Windows 10 Home Version 2004. Can you describe more system details? Version, type of input device used (mouse, trackpad, etc.)?
![Texture64_Win10_Export](https://user-images.githubusercontent.com/129774/103383802-faf12180-4aa8-11eb-9208-30593556854f.png)
