### ISSUE TITLE
Textures not displayed?!

### ISSUE THREAD

**Issue by Asortofcode** [queueRAM/Texture64#8]
Hi, Regarding the new 0.2 release I tried to view the textures of several games, including SM64 and MK64. Unfortunately, I've got only pixel gibberish, see the attached file. No matter the format (PAL/NTSC) or the color palette, it never seems to work. Any ideas?
![Texture64](https://user-images.githubusercontent.com/56174257/104320237-5cba7e00-54e2-11eb-9169-ef8d2e781814.png)

**Comment by queueRAM** [comment]
The ROM's asset data is compressed and spread throughout the ROM. You first need to decompress the data, then go to the correct offsets of the decompressed blocks. There are a couple uncompressed assets in SM64 for the intro starting at offset 0x258D80 in the ROM. Also ensure that your ROM is big-endian (.z64)
